version: "3"

services:

  crypt_fack:
    build: .
    ports:
      - 6666:6666
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7.29
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: crypt_fack_db
      MYSQL_ROOT_PASSWORD: p@sSw0rD
    volumes:
      - ./db_data:/var/lib/mysql
